[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  status = 200
 from = "/*"
  to = "/index.html"  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200    /*    /index.html   200    /*    /index.html   200